# Powerline Sleeve Detection Configuration

# Paths
paths:
  data_dir: "data"
  raw_images: "data/raw"
  labeled_images: "data/labeled"
  processed_dataset: "data/processed"
  models_dir: "models"
  results_dir: "results"

# Acquisition
acquisition:
  api_key: ${GOOGLE_API_KEY}  # Google Street View API key
  image_size: [640, 640]
  cache_enabled: true
  cache_dir: "data/cache"
  distance_interval: 10  # meters between consecutive images

# Labeling
labeling:
  tool: "labelme"  # Tool used for manual labeling
  classes: ["powerline", "sleeve"]
  auto_labeling:
    confidence_threshold: 0.5
    iou_threshold: 0.45

# Dataset
dataset:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  yolo_format: true
  augmentation:
    enabled: true
    rotation_range: 15
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]
    horizontal_flip: true
    vertical_flip: false

# Training
training:
  # Common parameters
  batch_size: 16
  epochs: 100
  image_size: [640, 640]
  patience: 15  # Early stopping
  optimizer: "Adam"
  learning_rate: 0.001
  device: "cuda"  # or "cpu"
  
  # Powerline detection model
  powerline:
    model_type: "yolov8n"
    pretrained: true
    classes: ["powerline"]
  
  # Sleeve detection model
  sleeve:
    model_type: "yolov8n"
    pretrained: true
    classes: ["sleeve"]
    two_stage: true  # Use two-stage detection (powerline first, then sleeve)

# Detection
detection:
  confidence_threshold: 0.4
  iou_threshold: 0.45
  max_detections: 100
  batch_size: 16
  ensemble:
    enabled: false
    models: []
    weights: []
    method: "weighted_boxes_fusion"

# Visualization
visualization:
  save_images: true
  draw_bounding_boxes: true
  line_thickness: 2
  text_size: 1.0
  map:
    enabled: true
    zoom_level: 15
    marker_size: 5

# Configuration for YOLOv8 Training

# --- Dataset Configuration ---
# Path to the YOLOv8 dataset YAML file (e.g., data.yaml)
# This file defines train/val/test paths and class names.
dataset_yaml_path: path/to/your/dataset/data.yaml  # *** ADJUST THIS PATH ***

# --- Model Configuration ---
# Pre-trained model to start from (e.g., yolov8n.pt, yolov8s.pt, yolov8m.pt)
# Or path to a previously trained model checkpoint (.pt file)
model_type: yolov8n.pt

# --- Training Hyperparameters ---
hyperparameters:
  epochs: 100          # Number of training epochs
  batch_size: 16       # Batch size (-1 for AutoBatch)
  image_size: 640      # Input image size (pixels)
  learning_rate: 0.01  # Initial learning rate (lr0)
  # Add other YOLOv8 train arguments here if needed (e.g., optimizer, patience, weight_decay)
  # See: https://docs.ultralytics.com/modes/train/#arguments

# --- Output Configuration ---
# Directory to save results (weights, logs, plots)
output:
  project_name: results/YOLOv8_Training  # Base directory for all experiments
  experiment_name: experiment1           # Specific name for this run (e.g., powerlines_v1, sleeves_augmented)

# --- Environment Configuration ---
# Device to use: 'cpu', '0' (for GPU 0), '0,1,2,3' (for multiple GPUs)
device: 'cpu' # *** ADJUST IF USING GPU *** 